import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'

await mkdir('artifacts', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const checks = []
for (const width of [1440, 1024, 768, 390]) {
  await page.setViewportSize({ width, height: 960 })
  await page.goto('http://127.0.0.1:5173/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Every input considered.')
  await expect(page.locator('.sidebar')).toHaveCount(0)
  await page.evaluate(() => document.fonts.ready)
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `Overflow at ${width}`)
  assert.equal(await page.evaluate(() => [...document.querySelectorAll('*')].filter(el => getComputedStyle(el).backgroundImage.includes('gradient')).length), 0)
  if ([1440, 390].includes(width)) await page.screenshot({ path: `artifacts/landing-${width}.png`, fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Open workspace', exact: true }).first().click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Project overview')
  await expect(page).toHaveURL(/#workspace\/project-overview$/)
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Project overview')
  await page.getByRole('button', { name: 'Go to landing page' }).click()
  await expect(page.locator('.landing')).toBeVisible()
  await page.getByRole('button', { name: 'Read the user guide' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('User guide')
  await page.goBack()
  await expect(page.locator('.landing')).toBeVisible()
  await page.getByRole('button', { name: 'Start a new project' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('replaces your current local project')
  const box = await page.getByRole('dialog').boundingBox()
  assert(box.x >= 0 && box.x + box.width <= width)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  checks.push(`${width}px: landing layout, workspace entry, reload, Home, guide, Back, and new-project dialog passed.`)
}
await page.goto('http://127.0.0.1:5173/#how-it-works')
await expect(page.locator('.landing')).toBeVisible()
await page.goto('http://127.0.0.1:5173/#workspace/zones')
await expect(page.getByRole('heading', { level: 1 })).toHaveText('Zones')
const before = await page.evaluate(() => JSON.parse(localStorage.getItem('mineral-project')).project)
await page.getByRole('button', { name: 'Go to landing page' }).click()
await page.getByRole('button', { name: 'Open workspace', exact: true }).first().click()
const after = await page.evaluate(() => JSON.parse(localStorage.getItem('mineral-project')).project)
assert.deepEqual(after, before)
assert.equal(errors.length, 0, errors.join('\n'))
checks.push('Direct workspace and workflow links work; entering and leaving the landing page preserves saved project data; no browser runtime errors.')
await writeFile('artifacts/landing-verification.txt', checks.join('\n'))
console.log(checks.join('\n'))
await browser.close()
