import { chromium, expect } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

await mkdir('artifacts', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } })
const errors = []
page.on('pageerror', error => errors.push(error.message))
await page.goto('http://127.0.0.1:5173/#workspace/project-overview')
await page.evaluate(() => document.fonts.ready)
const pages = ['Project overview', 'Design conditions', 'Zones', 'Construction', 'Internal loads', 'Air loads', 'Reference tables', 'Calculate', 'Results', 'Reports', 'Settings']
async function navigate(name, width = 1440) {
  if (width <= 900) await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: name === 'Zones' ? /^Zones/ : name, exact: name !== 'Zones' }).click()
  await page.getByRole('heading', { level: 1, name, exact: true }).waitFor()
  if (width <= 900) await expect.poll(() => page.locator('.sidebar').evaluate(el => el.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
}
const checks = []
for (const width of [1440, 1024, 768, 390]) {
  await page.setViewportSize({ width, height: width === 390 ? 844 : 1080 })
  for (const name of pages) {
    await navigate(name, width)
    const dimensions = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }))
    assert(dimensions.scroll <= dimensions.client, `${name} overflows at ${width}: ${JSON.stringify(dimensions)}`)
    const gradients = await page.evaluate(() => [...document.querySelectorAll('*')].filter(el => getComputedStyle(el).backgroundImage.includes('gradient')).length)
    assert.equal(gradients, 0, `${name} contains a gradient`)
    checks.push(`${name}: ${width}px, no page overflow or gradients`)
    if (['Project overview', 'Zones', 'Results', 'Design conditions'].includes(name) && [1440, 390].includes(width)) await page.screenshot({ path: `artifacts/${name.toLowerCase().replaceAll(' ', '-')}-${width}.png`, fullPage: true, animations: 'disabled' })
  }
}
await page.setViewportSize({ width: 1440, height: 1080 })
await navigate('Zones')
await page.getByRole('button', { name: 'Add zone', exact: true }).click()
await page.getByRole('dialog').getByLabel('Zone name', { exact: true }).fill('Test laboratory')
await page.getByRole('dialog').getByLabel('Floor area', { exact: true }).fill('90')
await page.getByRole('button', { name: 'Create zone', exact: true }).click()
await page.getByRole('heading', { name: 'Test laboratory', exact: true }).waitFor()
await page.getByLabel('Occupancy', { exact: true }).fill('12')
await page.getByRole('button', { name: 'Save zone inputs', exact: true }).click()
await page.getByRole('button', { name: 'Duplicate zone', exact: true }).click()
await page.getByRole('heading', { name: 'Test laboratory (copy)', exact: true }).waitFor()
await page.getByRole('button', { name: 'Delete zone', exact: true }).click()
await page.getByRole('dialog').getByRole('button', { name: 'Delete zone', exact: true }).click()
await expect(page.getByRole('dialog')).toHaveCount(0)
await navigate('Design conditions')
await page.getByLabel('Outdoor dry-bulb temperature', { exact: true }).fill('38')
await page.getByRole('button', { name: 'Save conditions' }).click()
await navigate('Results')
await page.getByText('Inputs have changed.', { exact: true }).waitFor()
await page.getByRole('button', { name: 'Recalculate', exact: true }).click()
await page.getByRole('button', { name: 'Run calculation', exact: true }).waitFor()
await expect(page.getByText('Inputs have changed.', { exact: true })).toHaveCount(0)
await page.getByRole('button', { name: 'Table', exact: true }).click()
assert.equal(await page.locator('.chart-table tbody tr').count(), 24)
await page.locator('.audit-row summary').first().click()
await page.locator('.audit-row[open] code').waitFor()
await navigate('Reports')
const downloaded = page.waitForEvent('download')
await page.getByRole('button', { name: 'Export hourly data (.csv)', exact: true }).click()
assert((await downloaded).suggestedFilename().endsWith('.csv'))
await page.reload()
await navigate('Zones')
await page.getByRole('button', { name: /Test laboratory/ }).waitFor()
await page.setViewportSize({ width: 390, height: 844 })
await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
assert.equal(await page.locator('.workspace').evaluate(el => el.inert), true)
await page.keyboard.press('Escape')
assert.equal(await page.locator('.workspace').evaluate(el => el.inert), false)
await page.getByRole('button', { name: 'Add zone', exact: true }).click()
const box = await page.getByRole('dialog').boundingBox()
assert(box.x >= 0 && box.x + box.width <= 390 && box.y >= 0 && box.y + box.height <= 844)
await page.keyboard.press('Escape')
assert.equal(errors.length, 0, errors.join('\n'))
checks.push('Zone create, save, duplicate and delete; recalculation; 24 hourly rows; formula expansion; CSV export; local persistence; mobile drawer inert state and Escape; mobile dialog fit: passed.')
await writeFile('artifacts/verification.txt', checks.join('\n'))
console.log(checks.join('\n'))
await browser.close()
