import { useState, useEffect, useRef } from 'react'
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BookOpen, Building2, Calculator, Check, CheckCircle2, ChevronRight, ChevronsLeft, Copy, FileText, FolderOpen, HelpCircle, Layers3, LayoutDashboard, Menu, MoreHorizontal, Plus, Save, Search, Settings2, Snowflake, Sun, Thermometer, Trash2, Upload, Users, Wind, X } from 'lucide-react'
import { Button, Field, Select, Notice, Empty, Modal, LoadChart, Breakdown } from './components'
import { initialProject, calculate, components, number, time, download } from './data'
import './App.css'
import Guide from './Guide'
import Landing from './Landing'

const navigation = [
  ['Project overview', LayoutDashboard], ['Design conditions', Thermometer], ['Zones', Layers3], ['Construction', Building2], ['Internal loads', Users], ['Air loads', Wind], ['Reference tables', BookOpen], ['Calculate', Calculator], ['Results', Activity], ['Reports', FileText], ['Settings', Settings2],
]
const descriptions = {
  'Project overview': 'A clear view of your building, design inputs and cooling demand.',
  'Design conditions': 'Set the environmental conditions used across all project zones.',
  Zones: 'Define each space and the inputs that shape its cooling demand.',
  Construction: 'Review envelope areas and thermal properties by zone.',
  'Internal loads': 'Manage occupancy, lighting and equipment heat gains.',
  'Air loads': 'Define outdoor air and infiltration for each conditioned space.',
  'Reference tables': 'Inspect the source values and assumptions behind your calculations.',
  Calculate: 'Review your inputs and run the illustrative design-day calculation.',
  Results: 'Trace the design cooling load from building peak to individual components.',
  Reports: 'Export a transparent record of your inputs, results and assumptions.',
  Settings: 'Manage project details and local project data.',
  'User guide': 'A practical introduction to your first project, calculation and report.',
}
function readProject() {
  try { const stored = JSON.parse(localStorage.getItem('mineral-project')); return stored?.version === 1 ? stored.project : initialProject } catch { return initialProject }
}
function pageFromLocation() {
  const hash = window.location.hash
  if (hash.startsWith('#guide-')) return 'User guide'
  if (hash.startsWith('#workspace')) return navigation.find(([name]) => `#workspace/${name.toLowerCase().replaceAll(' ', '-')}` === hash)?.[0] ?? 'Project overview'
  return 'Home'
}
function readRun() {
  try {
    const stored = JSON.parse(localStorage.getItem('mineral-project'))
    if (stored?.version === 1) return stored.run ?? null
  } catch { /* A new demonstration workspace can still open without storage. */ }
  return { result: calculate(initialProject), fingerprint: JSON.stringify(initialProject), at: null }
}
export default function App() {
  const [project, setProject] = useState(readProject)
  const [page, setPage] = useState(pageFromLocation)
  const [drawer, setDrawer] = useState(false)
  const [collapsed, setCollapsed] = useState(false)
  const [modal, setModal] = useState(null)
  const [selected, setSelected] = useState(project?.zones[0]?.id)
  const [query, setQuery] = useState('')
  const [toast, setToast] = useState('')
  const [storageError, setStorageError] = useState(false)
  const [run, setRun] = useState(readRun)
  const [running, setRunning] = useState(false)
  const [importError, setImportError] = useState('')
  const [referenceQuery, setReferenceQuery] = useState('')
  const importRef = useRef(null)
  const navRef = useRef(null)
  const menuRef = useRef(null)
  const workspaceRef = useRef(null)
  const live = project ? calculate(project) : null
  const result = run?.result
  const stale = run && run.fingerprint !== JSON.stringify(project)
  const area = project?.zones.reduce((sum, z) => sum + Number(z.area), 0) ?? 0
  useEffect(() => {
    const timer = setTimeout(() => { try { localStorage.setItem('mineral-project', JSON.stringify({ version: 1, project, run })); setStorageError(false) } catch { setStorageError(true) } }, 0)
    return () => clearTimeout(timer)
  }, [project, run])
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer) } }, [toast])
  useEffect(() => {
    const syncLocation = () => { setPage(pageFromLocation()); setDrawer(false); setModal(null) }
    window.addEventListener('popstate', syncLocation)
    window.addEventListener('hashchange', syncLocation)
    return () => { window.removeEventListener('popstate', syncLocation); window.removeEventListener('hashchange', syncLocation) }
  }, [])
  useEffect(() => {
    let expanded = []
    const before = () => { expanded = [...document.querySelectorAll('.report-preview details:not([open])')]; expanded.forEach(detail => { detail.open = true }) }
    const after = () => { expanded.forEach(detail => { detail.open = false }); expanded = [] }
    window.addEventListener('beforeprint', before)
    window.addEventListener('afterprint', after)
    return () => { window.removeEventListener('beforeprint', before); window.removeEventListener('afterprint', after) }
  }, [])
  useEffect(() => {
    if (!drawer) return
    const old = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    const workspace = workspaceRef.current
    const menu = menuRef.current
    workspace.inert = true
    navRef.current.querySelector('button').focus()
    const handleKey = e => {
      if (e.key === 'Escape') setDrawer(false)
      if (e.key === 'Tab') {
        const controls = [...navRef.current.querySelectorAll('button')].filter(el => el.getClientRects().length)
        if (e.shiftKey && document.activeElement === controls[0]) { e.preventDefault(); controls.at(-1).focus() }
        else if (!e.shiftKey && document.activeElement === controls.at(-1)) { e.preventDefault(); controls[0].focus() }
      }
    }
    document.addEventListener('keydown', handleKey)
    return () => { document.body.style.overflow = old; workspace.inert = false; document.removeEventListener('keydown', handleKey); menu?.focus() }
  }, [drawer])
  function navigate(next) {
    setPage(next); setDrawer(false); setQuery('')
    const hash = next === 'Home' ? '' : next === 'User guide' ? '#guide-start' : `#workspace/${next.toLowerCase().replaceAll(' ', '-')}`
    window.history.pushState(null, '', window.location.pathname + window.location.search + hash)
    window.scrollTo({ top: 0 })
  }
  function update(values) { setProject(p => ({ ...p, ...values })) }
  function updateZone(id, values) { setProject(p => ({ ...p, zones: p.zones.map(z => z.id === id ? { ...z, ...values } : z) })) }
  function calculateNow() {
    if (running) return
    if (!project.zones.length) { navigate('Zones'); return }
    setRunning(true)
    setTimeout(() => { setRun({ result: calculate(project), fingerprint: JSON.stringify(project), at: new Date().toISOString() }); setRunning(false); navigate('Results'); setToast('Calculation complete. Results reflect your current inputs.') }, 650)
  }
  function duplicate(zone) { const id = crypto.randomUUID(); update({ zones: [...project.zones, { ...zone, id, name: `${zone.name} (copy)` }] }); setSelected(id); setToast('Zone duplicated.') }
  function csv() {
    const rows = [['Hour', ...components.map(([, label]) => `${label} (kW)`), 'Total (kW)'], ...result.hours.map(h => [time(h.hour), ...components.map(([key]) => h[key].toFixed(4)), h.total.toFixed(4)])]
    download(`${project.code}-illustrative-loads.csv`, 'Illustrative steady-state model; not validated for equipment sizing\n' + rows.map(r => r.join(',')).join('\n'), 'text/csv')
  }
  async function importProject(e) {
    const file = e.target.files[0]
    if (!file) return
    try {
      const data = JSON.parse(await file.text())
      const p = data.project
      if (data.version !== 1 || !p || !Array.isArray(p.zones) || p.zones.length > 500) throw Error('Use a Mineral project JSON exported from this application.')
      for (const key of ['name', 'code', 'client', 'location', 'month']) if (typeof p[key] !== 'string' || !p[key].trim()) throw Error(`Missing project field: ${key}.`)
      for (const key of ['outdoor', 'indoor', 'humidity', 'deltaHumidity', 'safety', 'diversity']) if (typeof p[key] !== 'number' || !Number.isFinite(p[key])) throw Error(`Invalid project value: ${key}.`)
      if (p.humidity < 0 || p.humidity > 100 || p.safety < 0 || p.safety > 100 || p.diversity < 0 || p.diversity > 100 || p.deltaHumidity < 0 || p.deltaHumidity > 50) throw Error('Project adjustment or humidity value is outside its allowed range.')
      const ids = new Set()
      for (const z of p.zones) {
        for (const key of ['id', 'name', 'type', 'floor']) if (typeof z[key] !== 'string' || !z[key].trim()) throw Error(`A zone is missing ${key}.`)
        if (ids.has(z.id)) throw Error('Zone identifiers must be unique.')
        ids.add(z.id)
        for (const key of Object.keys(initialProject.zones[0]).filter(k => typeof initialProject.zones[0][k] === 'number')) if (typeof z[key] !== 'number' || !Number.isFinite(z[key]) || z[key] < 0 || z[key] > 1e6) throw Error(`Invalid ${key} in ${z.name}.`)
        if (z.shgc > 1 || !z.area || !z.height || !Number.isInteger(z.people)) throw Error(`Invalid geometry, occupancy or SHGC in ${z.name}.`)
      }
      setProject(p); setRun(null); setSelected(p.zones[0]?.id); setImportError(''); navigate('Project overview'); setToast('Project imported. Run a calculation to generate results.')
    } catch (error) { setImportError(error.message) }
    e.target.value = ''
  }
  if (page === 'Home') return <Landing project={project} onOpen={() => navigate('Project overview')} onGuide={() => navigate('User guide')} onNew={() => { navigate('Project overview'); setModal({ type: 'new' }) }} />
  const zone = project?.zones.find(z => z.id === selected) ?? project?.zones[0]
  const navContent = <><div className="brand"><div className="brand-mark"><Snowflake size={28} strokeWidth={1.6} /></div><div className="brand-copy"><b>mineral<span>.</span></b><span>Cooling load workspace</span></div><button className="icon-button mobile-close" aria-label="Close navigation" onClick={() => setDrawer(false)}><X size={20} /></button></div><button className="project-switch" onClick={() => setModal({ type: 'project' })} title="Project details"><Building2 size={19} /><span><strong>{project?.name ?? 'No project selected'}</strong><small>{project?.code ?? 'Create a project'}</small></span><MoreHorizontal size={18} /></button><div className="nav-caption">Workspace</div><nav aria-label="Main navigation">{navigation.map(([name, Icon], i) => <button key={name} className={`nav-item ${page === name ? 'active' : ''} ${i === 7 || i === 10 ? 'nav-separated' : ''}`} onClick={() => navigate(name)} aria-label={name} aria-current={page === name ? 'page' : undefined} title={name}><Icon size={19} strokeWidth={1.7} /><span>{name}</span>{name === 'Zones' && <small>{project?.zones.length ?? 0}</small>}{page === name && <i />}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span className="status-dot" /><span>Local workspace</span><span className="mono">v0.1</span></div><button className="nav-item" aria-label="User guide" onClick={() => navigate('User guide')}><HelpCircle size={19} /><span>User guide</span><ArrowUpRight size={15} /></button><button className="nav-item collapse-control" onClick={() => setCollapsed(!collapsed)} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}><ChevronsLeft size={19} className={collapsed ? 'rotate' : ''} /><span>Collapse sidebar</span></button></div></>
  return <div className={`app-shell ${collapsed ? 'is-collapsed' : ''}`}><a href="#main-content" className="skip-link">Skip to content</a>{drawer && <div className="drawer-backdrop" onClick={() => setDrawer(false)} />}<aside ref={navRef} className={`sidebar ${drawer ? 'open' : ''}`} role={drawer ? 'dialog' : undefined} aria-modal={drawer || undefined} aria-label="Workspace navigation">{navContent}</aside><div className="workspace" ref={workspaceRef}><header className="topbar"><div className="breadcrumbs"><button ref={menuRef} className="icon-button mobile-menu" aria-label="Open navigation" aria-expanded={drawer} onClick={() => setDrawer(true)}><Menu size={21} /></button><FolderOpen size={17} /><span>Projects</span><ChevronRight size={14} /><strong>{project?.name ?? 'New project'}</strong></div><div className="topbar-meta"><button className="icon-button" aria-label="Go to landing page" title="Mineral home" onClick={() => navigate('Home')}><Snowflake size={19} /></button><span className="save-state"><Check size={14} />{storageError ? 'Not saved' : 'Saved locally'}</span><span className="unit-tag mono">SI units</span><button className="icon-button" aria-label="Open user guide" onClick={() => navigate('User guide')}><HelpCircle size={19} /></button></div></header><main id="main-content" tabIndex={-1}><div className="page-heading"><div><div className="eyebrow"><span className="project-code mono">{project?.code ?? 'New workspace'}</span><span className="eyebrow-divider" />Cooling load analysis</div><h1>{page}</h1><p>{descriptions[page]}</p></div><div className="page-actions">{project && <>{['Project overview', 'Results'].includes(page) && <><Button icon={ArrowDownToLine} onClick={() => navigate('Reports')}>Export report</Button><Button variant="primary" icon={Calculator} onClick={calculateNow} disabled={running || !project.zones.length}>{running ? 'Calculating…' : stale ? 'Recalculate' : 'Run calculation'}</Button></>}{page === 'Zones' && <Button variant="primary" icon={Plus} onClick={() => setModal({ type: 'zone' })}>Add zone</Button>}{page === 'Reports' && <Button icon={ArrowDownToLine} variant="primary" disabled={!result || stale} onClick={() => window.print()}>Print / save PDF</Button>}</>}</div></div>
  {storageError && <Notice tone="danger" title="Local save failed.">Export your project from Settings to keep a copy.</Notice>}{importError && <Notice tone="danger" title="Failed project import.">{importError}</Notice>}
  {project && <div className="demo-banner"><span><InfoMark /><strong>Demonstration workspace</strong><span className="demo-detail">Illustrative inputs and a simplified calculation model.</span></span><button onClick={() => setModal({ type: 'help' })}>View assumptions <ArrowUpRight size={14} /></button></div>}
  {page === 'User guide' ? <Guide navigate={navigate} hasProject={!!project} /> : !project ? <Empty icon={FolderOpen} title="Start with a project">Create a project to define design conditions and add your first zone.</Empty> : <>
    {stale && ['Project overview', 'Results', 'Reports'].includes(page) && <Notice title="Inputs have changed.">Run the calculation again to update these results.</Notice>}
    {['Project overview', 'Results'].includes(page) && (result && result.zones.length && !stale ? <>
      <section className="result-summary"><div className="dominant-result"><div className="result-label"><span className="status-dot" />Total design cooling load<Snowflake size={20} /></div><div className="major-value">{number(result.design)} <span>kW</span></div><p>Includes {number(project.safety, 0)}% safety · {number(project.diversity, 0)}% diversity</p><div className="peak-caption"><Sun size={15} />Design day peak <strong>{project.month} · {time(result.peak.hour)}</strong></div></div><div className="secondary-results"><div><span>Sensible load</span><strong>{number(result.sensible)} <small>kW</small></strong><p>Heat gain at coincident peak</p></div><div><span>Latent load</span><strong>{number(result.peak.latent)} <small>kW</small></strong><p>Moisture removal at peak</p></div><div><span>Sensible heat ratio</span><strong>{number(result.peak.total ? result.sensible / result.peak.total : 0, 3)} <small>SHR</small></strong><p>Sensible / total load</p></div></div></section>
      <div className="chart-grid"><LoadChart result={result} month={project.month} /><Breakdown result={result} /></div>
      <div className="section-heading"><div><h2>{page === 'Results' ? 'Zone comparison' : 'Zone overview'} <span className="count-tag">{project.zones.length} zones</span></h2><p>Individual zone peaks before project adjustments.</p></div><Button variant="ghost" icon={ArrowRight} onClick={() => navigate('Zones')}>Manage zones</Button></div><section className="panel zone-table-panel"><div className="table-toolbar"><div className="search-input"><Search size={16} /><input aria-label="Search zones" placeholder="Find a zone…" value={query} onChange={e => setQuery(e.target.value)} /></div><span className="muted">Total floor area <b className="mono">{number(area, 0)} m²</b></span></div><div className="table-scroll"><table><caption className="sr-only">Zone areas and individual peak cooling loads</caption><thead><tr><th>Zone name</th><th>Space type</th><th className="numeric">Area (m²)</th><th className="numeric">Sensible (kW)</th><th className="numeric">Latent (kW)</th><th className="numeric">Total (kW)</th><th>Peak hour</th><th><span className="sr-only">Edit</span></th></tr></thead><tbody>{result.zones.filter(z => z.name.toLowerCase().includes(query.toLowerCase())).map((z, i) => <tr key={z.id}><td><button className="zone-link" onClick={() => { setSelected(z.id); navigate('Zones') }}><span className="zone-number mono">{String(i + 1).padStart(2, '0')}</span><span><strong>{z.name}</strong><small>{z.floor}</small></span></button></td><td><span className="type-label">{z.type}</span></td><td className="numeric">{number(z.area, 0)}</td><td className="numeric">{number(z.peak.total - z.peak.latent)}</td><td className="numeric">{number(z.peak.latent)}</td><td className="numeric emphasis">{number(z.peak.total)}</td><td className="mono">{time(z.peak.hour)}</td><td><button className="icon-button" aria-label={`Edit ${z.name}`} onClick={() => { setSelected(z.id); navigate('Zones') }}><ChevronRight size={17} /></button></td></tr>)}</tbody><tfoot><tr><th colSpan="2">Non-coincident total</th><td className="numeric">{number(area, 0)}</td><td className="numeric">{number(result.zones.reduce((s, z) => s + z.peak.total - z.peak.latent, 0))}</td><td className="numeric">{number(result.zones.reduce((s, z) => s + z.peak.latent, 0))}</td><td className="numeric emphasis">{number(result.nonCoincident)}</td><td colSpan="2">Sum of zone peaks</td></tr></tfoot></table>{query && !result.zones.some(z => z.name.toLowerCase().includes(query.toLowerCase())) && <p className="no-search">No zones match “{query}”.</p>}</div></section>
      {page === 'Project overview' ? <div className="overview-bottom"><section className="conditions-strip"><div className="section-heading"><h2>Design conditions</h2><button className="text-button" onClick={() => navigate('Design conditions')}>Edit conditions <ArrowUpRight size={14} /></button></div><div className="condition-values"><div><span>Location</span><strong>{project.location}</strong></div><div><span>Outdoor dry-bulb</span><strong className="mono">{number(project.outdoor, 1)} °C</strong></div><div><span>Indoor dry-bulb</span><strong className="mono">{number(project.indoor, 1)} °C</strong></div><div><span>Indoor relative humidity</span><strong className="mono">{number(project.humidity, 0)} %</strong></div></div></section></div> : <><section className="panel padded"><h2>Peak aggregation & adjustments</h2><dl className="audit-grid"><div><dt>Coincident peak</dt><dd>{number(result.peak.total)} kW</dd></div><div><dt>Non-coincident peak</dt><dd>{number(result.nonCoincident)} kW</dd></div><div><dt>Safety factor</dt><dd>× {number(1 + project.safety / 100)}</dd></div><div><dt>Diversity factor</dt><dd>× {number(project.diversity / 100)}</dd></div></dl></section><Audit result={result} project={project} /><section className="panel padded"><h2>Calculation audit trail</h2><p className="muted">{run.at ? `Calculated ${new Date(run.at).toLocaleString()}.` : 'Initial demonstration calculation.'} Local model · revision 0.1 · {result.zones.length} zones · 24 hourly steps.</p><p>Design load = coincident peak × safety factor × diversity factor</p><code>{number(result.peak.total, 4)} × {number(1 + project.safety / 100)} × {number(project.diversity / 100)} = {number(result.design, 4)} kW</code></section></>}
    </> : <Empty icon={Activity} title={stale ? 'Results need recalculation' : project.zones.length ? 'No calculation performed' : 'No zones added'} action={project.zones.length ? 'Run calculation' : 'Add first zone'} onAction={project.zones.length ? calculateNow : () => setModal({ type: 'zone' })}>Add design inputs and run a calculation to see your cooling-load profile.</Empty>)}
    {page === 'Design conditions' && <DesignForm project={project} onSave={values => { update(values); setToast('Design conditions saved.') }} />}
    {page === 'Zones' && (zone ? <div className="zone-editor"><aside className="zone-list panel"><div className="panel-heading"><h2>Project zones</h2><span className="count-tag">{project.zones.length}</span></div>{project.zones.map((z, i) => <button key={z.id} aria-pressed={zone.id === z.id} onClick={() => setSelected(z.id)}><span className="mono zone-number">{String(i + 1).padStart(2, '0')}</span><span><strong>{z.name}</strong><small>{number(z.area, 0)} m² · {z.type}</small></span><ChevronRight size={15} /></button>)}</aside><ZoneForm key={zone.id} zone={zone} onSave={values => { updateZone(zone.id, values); setToast('Zone inputs saved.') }} onDuplicate={() => duplicate(zone)} onDelete={() => setModal({ type: 'delete', zone })} /><aside className="zone-summary panel padded"><h3>Saved input summary</h3><p className="muted">{zone.name}</p><dl><div><dt>Floor area</dt><dd>{number(zone.area, 0)} m²</dd></div><div><dt>Volume</dt><dd>{number(zone.area * zone.height, 0)} m³</dd></div><div><dt>Occupancy</dt><dd>{zone.people} people</dd></div><div><dt>Outdoor airflow</dt><dd>{number(zone.airflow, 0)} L/s</dd></div></dl><div className="mini-result"><span>Illustrative zone peak</span><strong>{number(live.zones.find(z => z.id === zone.id)?.peak.total ?? 0)} <small>kW</small></strong></div><p className="field-hint">Updates when you save zone inputs. Before safety and diversity adjustments.</p></aside></div> : <Empty icon={Layers3} title="Add your first zone" action="Add zone" onAction={() => setModal({ type: 'zone' })}>A zone represents a space with common design conditions and occupancy.</Empty>)}
    {['Construction', 'Internal loads', 'Air loads'].includes(page) && <InputWorksheet page={page} project={project} onEdit={id => { setSelected(id); navigate('Zones') }} />}
    {page === 'Reference tables' && <><Notice tone="information" title="No reference dataset imported.">This workspace uses explicit demonstration assumptions. Licensed CLTD, SCL and CLF datasets are not included.</Notice><section className="panel"><div className="panel-heading"><div><h2>Demonstration model constants</h2><p>Local illustrative model · revision 0.1 · no published reference edition</p></div></div><div className="table-toolbar"><div className="search-input"><Search size={16} /><input placeholder="Search constants…" aria-label="Search reference constants" value={referenceQuery} onChange={e => setReferenceQuery(e.target.value)} /></div></div><div className="table-scroll"><table><thead><tr><th>Reference key</th><th>Parameter</th><th className="numeric">Value</th><th>Unit</th><th>Source</th></tr></thead><tbody>{[['AIR_DENSITY', 'Air density', '1.2', 'kg/m³'], ['AIR_CP', 'Air specific heat', '1.006', 'kJ/kg·K'], ['H_FG', 'Vaporization enthalpy', '2501', 'kJ/kg'], ['PERSON_S', 'Sensible gain per person', '75', 'W/person'], ['PERSON_L', 'Latent gain per person', '55', 'W/person'], ['SOLAR_MAX', 'Peak incident solar radiation', '600', 'W/m²']].filter(row => row.join(' ').toLowerCase().includes(referenceQuery.toLowerCase())).map(row => <tr key={row[0]}>{row.map((cell, i) => <td key={i} className={i === 0 || i === 2 ? 'mono' : ''}>{cell}</td>)}<td>Demonstration assumption</td></tr>)}</tbody></table></div></section><section className="panel padded"><h2>About reference datasets</h2><p>Reference-table import and validated CLTD/SCL/CLF lookups are not implemented in this version. The current model exposes its inputs and formulas for interface evaluation.</p><Button variant="ghost" icon={BookOpen} onClick={() => setModal({ type: 'help' })}>Read model assumptions</Button></section></>}
    {page === 'Calculate' && <><section className="panel padded calculation-panel"><div><h2>Ready to calculate</h2><p className="muted">One design day. All project zones. A fully inspectable result.</p></div><div className="checklist"><p><CheckCircle2 size={18} />{project.zones.length} zones defined <span className="mono">{number(area, 0)} m²</span></p><p><CheckCircle2 size={18} />Design temperatures <span className="mono">{project.outdoor} / {project.indoor} °C</span></p><p><CheckCircle2 size={18} />Calculation period <span className="mono">00:00–23:00</span></p></div><Notice title="Illustrative calculation only.">The steady-state model does not account for thermal storage, orientation or reference-table corrections. Results are not suitable for equipment sizing.</Notice>{running ? <div className="skeleton" role="status" aria-label="Calculating hourly loads"><span /><span /><span /></div> : <Button variant="primary" icon={Calculator} disabled={!project.zones.length} onClick={calculateNow}>Calculate all zones</Button>}</section></>}
    {page === 'Reports' && <><section className="panel report-preview"><div className="report-brand"><Snowflake size={22} />mineral<span className="mono">{project.code}</span></div><div className="report-title"><span className="eyebrow">Engineering calculation record</span><h2>{project.name}</h2><p>{project.client} · {project.location}</p></div><Notice title="Demonstration report">Illustrative steady-state results. Not validated for equipment selection.</Notice>{result && !stale ? <><dl className="audit-grid"><div><dt>Design cooling load</dt><dd>{number(result.design)} kW</dd></div><div><dt>Peak design hour</dt><dd>{project.month} · {time(result.peak.hour)}</dd></div><div><dt>Total floor area</dt><dd>{number(area, 0)} m²</dd></div><div><dt>Zones</dt><dd>{project.zones.length}</dd></div></dl><Audit result={result} project={project} /></> : <p>No calculation performed. Run a calculation before exporting results.</p>}</section><div className="export-options"><Button icon={ArrowDownToLine} disabled={!result || stale} onClick={csv}>Export hourly data (.csv)</Button><Button icon={ArrowDownToLine} onClick={() => download(`${project.code}.json`, JSON.stringify({ version: 1, project }, null, 2))}>Export project (.json)</Button></div></>}
    {page === 'Settings' && <><ProjectForm key={project.code} project={project} onSave={values => { update(values); setToast('Project details saved.') }} /><section className="panel padded"><h2>Project data</h2><p className="muted">Your project is stored in this browser. Export a copy to transfer it to another device.</p><div className="export-options"><Button icon={ArrowDownToLine} onClick={() => download(`${project.code}.json`, JSON.stringify({ version: 1, project }, null, 2))}>Export project</Button><Button icon={Upload} onClick={() => setModal({ type: 'import' })}>Import project</Button><Button icon={Plus} onClick={() => setModal({ type: 'new' })}>New project</Button><Button variant="danger-outline" icon={Trash2} onClick={() => setModal({ type: 'reset' })}>Delete project</Button></div></section></>}
  </>}
  {!project && page !== 'User guide' && <div className="empty-actions"><Button variant="primary" icon={Plus} onClick={() => setModal({ type: 'new' })}>Create project</Button><Button icon={Upload} onClick={() => importRef.current.click()}>Import project</Button></div>}
  <footer className="page-footer"><span><Snowflake size={14} />Mineral · Cooling load workspace</span><span>Illustrative model <i /> SI units <i /> Local storage</span></footer></main></div>
  <input ref={importRef} type="file" accept=".json,application/json" className="sr-only" aria-label="Import project JSON" onChange={importProject} />
  {toast && <div className="toast" role="status"><CheckCircle2 size={18} />{toast}<button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast('')}><X size={16} /></button></div>}
  {modal && <Modal title={{ zone: 'Add zone', delete: 'Delete zone?', help: 'Calculation guide', project: 'Project details', new: 'Create project', reset: 'Delete project?', import: 'Import a project?' }[modal.type]} onClose={() => setModal(null)}>
    {modal.type === 'help' && <div className="modal-body prose"><Notice title="Demonstration model">For reviewing this interface. Not for equipment sizing or client design certification.</Notice><h3>How this workspace calculates</h3><p>Hourly steady-state heat gains are summed for each zone. The coincident peak is the largest building total across 24 hours. Non-coincident load is the sum of individual zone peaks.</p><h3>Explicit assumptions</h3><ul><li>Uniform solar exposure; peak radiation 600 W/m² with a sinusoidal daytime profile.</li><li>Outdoor temperature peaks at 15:00, with a 16 °C daily range.</li><li>Full occupancy and lighting from 08:00 to 17:00; 25% at 07:00 and 18:00.</li><li>Equipment uses 15% of entered density outside full occupancy.</li><li>People contribute 75 W sensible and 55 W latent each.</li><li>All negative conduction loads are clamped to zero.</li><li>Month is a design-day label; humidity load uses the entered humidity-ratio difference.</li><li>No thermal storage, orientation, shading schedules or CLTD/SCL/CLF corrections.</li></ul><h3>Inspect and export</h3><p>Results include hourly values, component formulas and calculation inputs. Save a project JSON for a portable copy, or export hourly values as CSV.</p><Button variant="primary" onClick={() => setModal(null)}>Understood</Button></div>}
    {modal.type === 'zone' && <NewZone onCancel={() => setModal(null)} onSave={values => { const id = crypto.randomUUID(); update({ zones: [...project.zones, { ...initialProject.zones[0], ...values, id, people: 0, lighting: 0, equipment: 0, airflow: 0, infiltration: 0, wall: 0, roof: 0, glass: 0 }] }); setSelected(id); setModal(null); navigate('Zones') }} />}
    {modal.type === 'delete' && <div className="modal-body"><p>Delete <strong>{modal.zone.name}</strong> and its load inputs? This action cannot be undone.</p><div className="dialog-actions"><Button onClick={() => setModal(null)}>Cancel</Button><Button variant="danger" icon={Trash2} onClick={() => { update({ zones: project.zones.filter(z => z.id !== modal.zone.id) }); setModal(null); setToast('Zone deleted.') }}>Delete zone</Button></div></div>}
    {modal.type === 'reset' && <div className="modal-body"><p>Delete this project and all its zones from this browser? Export a copy first if you need to keep your work.</p><div className="dialog-actions"><Button onClick={() => setModal(null)}>Cancel</Button><Button variant="danger" onClick={() => { setProject(null); setRun(null); setModal(null); navigate('Project overview') }}>Delete project</Button></div></div>}
    {modal.type === 'import' && <div className="modal-body"><p>Importing replaces the project in this browser. Export your current project first if you need to keep it.</p><div className="dialog-actions"><Button onClick={() => setModal(null)}>Cancel</Button><Button variant="primary" onClick={() => { setModal(null); importRef.current.click() }}>Choose project file</Button></div></div>}
    {modal.type === 'project' && <div className="modal-body"><p><strong>{project?.name ?? 'No project'}</strong></p><p className="mono muted">{project?.code}</p><p>{project?.client}</p><p>{project?.location}</p><div className="dialog-actions"><Button onClick={() => { setModal(null); navigate('Settings') }}>Project settings</Button><Button variant="primary" onClick={() => setModal({ type: 'new' })}>New project</Button></div></div>}
    {modal.type === 'new' && <div className="modal-body">{project && <Notice>Creating a project replaces your current local project. Export it from Settings to keep a copy.</Notice>}<ProjectForm project={{ name: '', code: '', client: '', location: '' }} onSave={values => { setProject({ ...initialProject, ...values, zones: [] }); setRun(null); setModal(null); navigate('Design conditions') }} /></div>}
  </Modal>}</div>
}
function InfoMark() { return <span className="demo-symbol" aria-hidden="true">i</span> }

function DesignForm({ project, onSave }) {
  const [draft, setDraft] = useState(project)
  const field = key => value => setDraft(d => ({ ...d, [key]: value }))
  return <form className="panel form-panel" onSubmit={e => { e.preventDefault(); onSave(Object.fromEntries(['outdoor', 'indoor', 'humidity', 'deltaHumidity', 'month', 'safety', 'diversity', 'location'].map(key => [key, draft[key]]))) }}><section><h2>Design environment</h2><p className="muted">Project-wide conditions for the illustrative design day.</p><div className="form-grid"><Field label="Location" type="text" value={draft.location} onChange={field('location')} /><Select label="Design month" value={draft.month} options={['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']} onChange={field('month')} /><Field label="Outdoor dry-bulb temperature" unit="°C" min={-40} max={65} value={draft.outdoor} onChange={field('outdoor')} hint="Maximum outdoor temperature for the design day." /><Field label="Indoor dry-bulb temperature" unit="°C" min={0} max={40} value={draft.indoor} onChange={field('indoor')} /><Field label="Indoor relative humidity" unit="%" max={100} value={draft.humidity} onChange={field('humidity')} hint="Recorded design target; not used to derive humidity ratio." /><Field label="Outdoor–indoor humidity ratio difference" unit="g/kg" max={50} value={draft.deltaHumidity} onChange={field('deltaHumidity')} hint="Used directly in ventilation and infiltration latent loads." /></div></section><section><h2>Design adjustments</h2><div className="form-grid"><Field label="Safety allowance" unit="%" max={100} value={draft.safety} onChange={field('safety')} hint="Applied to the coincident building peak." /><Field label="Diversity factor" unit="%" max={100} value={draft.diversity} onChange={field('diversity')} hint="100% means no diversity reduction." /></div></section><div className="form-footer"><span className="muted">Changes apply to all zones.</span><Button type="submit" variant="primary" icon={Save}>Save conditions</Button></div></form>
}
function ProjectForm({ project, onSave }) {
  const [draft, setDraft] = useState(project)
  return <form className="panel form-panel" onSubmit={e => { e.preventDefault(); onSave(Object.fromEntries(['name', 'code', 'client', 'location'].map(key => [key, draft[key].trim()]))) }}><section><h2>Basic information</h2><div className="form-grid">{[['name', 'Project name'], ['code', 'Project number'], ['client', 'Client'], ['location', 'Location']].map(([key, label]) => <Field key={key} label={label} type="text" pattern=".*\S.*" value={draft[key]} onChange={value => setDraft(d => ({ ...d, [key]: value }))} />)}</div></section><div className="form-footer"><Button variant="primary" icon={Save} type="submit">{project.name ? 'Save project details' : 'Create project'}</Button></div></form>
}
function NewZone({ onSave, onCancel }) {
  const [draft, setDraft] = useState({ name: '', area: '', height: 3, type: 'Office', floor: 'Level 01' })
  return <form className="modal-body" onSubmit={e => { e.preventDefault(); onSave(draft) }}><div className="form-grid"><Field label="Zone name" type="text" value={draft.name} onChange={name => setDraft({ ...draft, name })} /><Select label="Space type" value={draft.type} onChange={type => setDraft({ ...draft, type })} options={['Office', 'Meeting', 'Reception', 'Support', 'Other']} /><Field label="Floor area" unit="m²" min={0.1} value={draft.area} onChange={area => setDraft({ ...draft, area })} /><Field label="Ceiling height" unit="m" min={0.1} value={draft.height} onChange={height => setDraft({ ...draft, height })} /></div><p className="field-hint">Add envelope, occupancy and airflow inputs after creating the zone.</p><div className="dialog-actions"><Button onClick={onCancel}>Cancel</Button><Button variant="primary" type="submit" icon={Plus}>Create zone</Button></div></form>
}
function ZoneForm({ zone, onSave, onDuplicate, onDelete }) {
  const [draft, setDraft] = useState(zone)
  const field = key => value => setDraft(d => ({ ...d, [key]: value }))
  return <form className="panel form-panel zone-form" onSubmit={e => { e.preventDefault(); onSave(draft) }}><div className="panel-heading"><h2>{zone.name}</h2><div className="row-actions"><button className="icon-button" aria-label="Duplicate zone" onClick={onDuplicate} type="button"><Copy size={17} /></button><button className="icon-button danger-text" aria-label="Delete zone" onClick={onDelete} type="button"><Trash2 size={17} /></button></div></div><section><h3>Basic information & geometry</h3><div className="form-grid"><Field label="Zone name" type="text" value={draft.name} onChange={field('name')} /><Select label="Space type" value={draft.type} options={['Office', 'Meeting', 'Reception', 'Support', 'Other']} onChange={field('type')} /><Field label="Floor area" unit="m²" min={0.1} value={draft.area} onChange={field('area')} /><Field label="Ceiling height" unit="m" min={0.1} value={draft.height} onChange={field('height')} /></div></section><section><h3>Envelope & thermal properties</h3><p className="field-hint">Aggregated areas for each construction type. Wall area excludes glazing.</p><div className="form-grid">{[['wall', 'Net wall area', 'm²'], ['uWall', 'Wall U-value', 'W/m²·K'], ['roof', 'Roof area', 'm²'], ['uRoof', 'Roof U-value', 'W/m²·K'], ['glass', 'Glazing area', 'm²'], ['uGlass', 'Glazing U-value', 'W/m²·K'], ['shgc', 'Solar heat gain coefficient', 'ratio']].map(([key, label, unit]) => <Field key={key} label={label} unit={unit} max={key === 'shgc' ? 1 : undefined} value={draft[key]} onChange={field(key)} />)}</div></section><section><h3>Internal loads</h3><div className="form-grid">{[['people', 'Occupancy', 'people'], ['lighting', 'Lighting power density', 'W/m²'], ['equipment', 'Equipment power density', 'W/m²']].map(([key, label, unit]) => <Field key={key} label={label} unit={unit} step={key === 'people' ? 1 : 'any'} value={draft[key]} onChange={field(key)} />)}</div></section><section><h3>Air loads</h3><div className="form-grid"><Field label="Ventilation airflow" unit="L/s" value={draft.airflow} onChange={field('airflow')} /><Field label="Infiltration airflow" unit="L/s" value={draft.infiltration} onChange={field('infiltration')} /></div></section><details className="form-details"><summary>Schedule assumptions</summary><p>Full occupancy 08:00–17:00; 25% at 07:00 and 18:00. Equipment standby is 15%. Schedule editing is not available in this demonstration model.</p></details><div className="form-footer"><Button variant="primary" type="submit" icon={Save}>Save zone inputs</Button></div></form>
}
function InputWorksheet({ page, project, onEdit }) {
  const columns = page === 'Construction' ? [['wall', 'Wall (m²)'], ['roof', 'Roof (m²)'], ['glass', 'Glazing (m²)'], ['uWall', 'Wall U (W/m²·K)'], ['uRoof', 'Roof U (W/m²·K)'], ['uGlass', 'Glass U (W/m²·K)'], ['shgc', 'SHGC']] : page === 'Internal loads' ? [['people', 'People'], ['lighting', 'Lighting (W/m²)'], ['equipment', 'Equipment (W/m²)']] : [['airflow', 'Ventilation (L/s)'], ['infiltration', 'Infiltration (L/s)']]
  return <><section className="panel"><div className="panel-heading"><div><h2>{page === 'Construction' ? 'Envelope schedule' : page === 'Internal loads' ? 'Occupancy & power schedule' : 'Outdoor air schedule'}</h2><p>Edit a zone to change its load inputs.</p></div></div>{project.zones.length ? <div className="table-scroll"><table><thead><tr><th>Zone</th>{columns.map(([key, label]) => <th key={key} className="numeric">{label}</th>)}<th><span className="sr-only">Actions</span></th></tr></thead><tbody>{project.zones.map(z => <tr key={z.id}><th scope="row">{z.name}</th>{columns.map(([key]) => <td key={key} className="numeric">{number(z[key], ['people', 'wall', 'roof', 'glass'].includes(key) ? 0 : 2)}</td>)}<td><Button variant="ghost" onClick={() => onEdit(z.id)}>Edit <ChevronRight size={14} /></Button></td></tr>)}</tbody></table></div> : <Empty title="No zone inputs yet">Add a zone from the Zones page to begin.</Empty>}</section><Notice tone="information">{page === 'Construction' ? 'Areas are aggregated by zone. U-values and solar heat gain coefficients are entered directly; no reference-table corrections are applied.' : page === 'Internal loads' ? 'The demonstration schedule is fully occupied from 08:00 to 17:00. People gains are 75 W sensible and 55 W latent per person.' : 'Ventilation follows occupancy. Infiltration is constant throughout the day. Airflow is expressed in litres per second.'}</Notice></>
}
function Audit({ result, project }) {
  const formula = { envelope: 'Q = (A_wall × U_wall + A_roof × U_roof + A_glass × U_glass) × ΔT / 1000', solar: 'Q = A_glass × SHGC × 600 × solar profile / 1000', people: 'Q = people × 75 × occupancy / 1000', lighting: 'Q = floor area × lighting density × occupancy / 1000', equipment: 'Q = floor area × equipment density × (0.15 + 0.85 × occupancy) / 1000', ventilation: 'Q = 1.2 × 1.006 × airflow × ΔT × occupancy / 1000', infiltration: 'Q = 1.2 × 1.006 × infiltration airflow × ΔT / 1000', latent: 'Q = [people × 55 × occupancy + 1.2 × 2501 × (ventilation × occupancy + infiltration) × Δw / 1000] / 1000' }
  const hour = result.peak.hour
  const occupancy = hour >= 8 && hour < 18 ? 1 : hour === 7 || hour === 18 ? 0.25 : 0
  return <section className="audit-section"><h2>Detailed calculation worksheet</h2><p className="muted">Expand a component to inspect the formula and zone contributions at {time(hour)}.</p>{components.map(([key, label]) => <details key={key} className="audit-row"><summary><span><i style={{ background: `var(--color-${key})` }} />{label}</span><span className="mono">{number(result.peak[key])} kW<ChevronRight size={16} /></span></summary><div className="audit-content"><code>{formula[key]}</code><p className="muted">Source: demonstration model, revision 0.1. No published edition or lookup correction applied.</p><p className="mono">ΔT = {number(Math.max(0, project.outdoor - 8 + 8 * Math.cos((hour - 15) * Math.PI / 12) - project.indoor), 4)} K · Occupancy = {occupancy} · Δw = {project.deltaHumidity} g/kg</p><div className="table-scroll"><table><thead><tr><th>Zone</th><th className="numeric">Component load (kW)</th></tr></thead><tbody>{result.zones.map(z => <tr key={z.id}><td>{z.name}</td><td className="numeric">{number(z.hours[hour][key], 4)}</td></tr>)}</tbody></table></div></div></details>)}<div className="assumptions"><h3>Assumptions & warnings</h3><p>This model uses uniform solar exposure and fixed occupancy schedules. It excludes thermal storage, orientation and CLTD/SCL/CLF corrections. Confirm all inputs and use a validated method before equipment sizing.</p></div></section>
}
