import { ArrowRight, ArrowUpRight, BookOpen, Check, FileDown, Layers3, Snowflake } from 'lucide-react'
import { Button } from './components'
import './Landing.css'

export default function Landing({ onOpen, onNew, onGuide, project }) {
  return <div className="landing"><a className="skip-link" href="#landing-main">Skip to content</a><header className="landing-header"><a className="landing-brand" href="#" aria-label="Mineral home"><Snowflake size={28} strokeWidth={1.6} /><span>mineral<span className="brand-period">.</span></span></a><nav aria-label="Landing navigation"><a href="#how-it-works">How it works</a><button onClick={onGuide}>User guide <ArrowUpRight size={14} /></button><Button onClick={onOpen}>Open workspace <ArrowRight size={16} /></Button></nav></header>
    <main id="landing-main" className="landing-main" tabIndex={-1}>
      <section className="landing-hero"><div className="landing-intro"><div className="landing-kicker"><span className="status-dot" />A workspace for cooling-load analysis</div><h1>Every input considered.<br /><span>Every load explained.</span></h1><p>Bring your building’s geometry, conditions and heat gains into one clear workspace. Follow the calculation from the first zone to the final result.</p><div className="landing-actions"><Button variant="primary" onClick={onOpen}>Open workspace <ArrowRight size={17} /></Button><Button variant="ghost" icon={BookOpen} onClick={onGuide}>Read the user guide</Button></div><div className="landing-reassurance"><span><Check size={14} />No account required</span><span><Check size={14} />Projects saved in your browser</span></div></div>
        <div className="landing-drawing"><div className="drawing-heading"><span className="mono">01 / The building envelope</span><span>Concept diagram</span></div><svg viewBox="0 0 520 340" role="img" aria-labelledby="building-title building-desc"><title id="building-title">Heat gains in a conditioned space</title><desc id="building-desc">A technical section of a room, showing solar gain through glazing, envelope heat transfer through the roof, outdoor air, and internal gains from people and equipment.</desc><defs><marker id="heat-arrow" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" /></marker></defs><g className="drawing-guides"><path d="M66 274H462M103 63V303M424 63V303M73 285H452" /><path d="M93 82H434" strokeDasharray="3 5" /></g><g className="drawing-shell"><path d="M106 273V101H425V273H106Z" /><path d="M106 101L128 79H448V249L425 273M425 101L448 79M106 273L128 249H448M128 249V125" /><path d="M112 107H418V265H112Z" /><path d="M128 249H425" /></g><path className="drawing-roof" d="M106 101L128 79H448L425 101Z" /><g className="drawing-window"><path d="M106 133L128 116V206L106 223Z" /><path d="M106 178L128 161M117 125V214" /></g><g className="drawing-furniture"><path d="M209 217H319V225H209ZM220 225V250M308 225V250M252 217V190H285V217M252 212H285" /><path d="M353 214H377V235H353ZM357 235V250M373 235V250" /><circle cx="365" cy="187" r="9" /><path d="M354 212V203Q365 196 376 203V212" /></g><g className="drawing-heat"><path d="M50 132L154 178M53 163L152 207M268 37V122M398 150H346" markerEnd="url(#heat-arrow)" /><path d="M257 187V160M279 187V160M365 170V147" markerEnd="url(#heat-arrow)" /></g><g className="drawing-labels"><text x="34" y="110">Solar gain</text><text x="284" y="42">Envelope</text><text x="328" y="135">Outdoor air</text><text x="224" y="295">Internal gains</text></g><g className="drawing-dimensions"><path d="M107 310H425M107 305V315M425 305V315" /><text x="264" y="329" textAnchor="middle">One space. Connected inputs.</text></g></svg><div className="drawing-footer"><span className="mono">Geometry → Heat gains → Cooling load</span><Snowflake size={17} /></div></div>
      </section>
      <section className="landing-capabilities" aria-label="Workspace capabilities"><div><Layers3 size={20} /><span><strong>A building, organised by zone</strong><small>Geometry, envelope and loads in one place.</small></span></div><div><BookOpen size={20} /><span><strong>Calculations you can inspect</strong><small>Hourly values and component formulas.</small></span></div><div><FileDown size={20} /><span><strong>A record you can keep</strong><small>Project JSON, hourly CSV and printable reports.</small></span></div></section>
      <section className="landing-workflow" id="how-it-works"><div className="landing-section-heading"><div><span className="landing-kicker mono">From inputs to understanding</span><h2>A practical path through the calculation.</h2></div><p>Start with the supplied example, or bring your own project inputs. Keep the assumptions visible at every step.</p></div><ol><li><span className="step-number mono">01</span><h3>Define the spaces</h3><p>Set your design conditions and divide the building into zones. Add areas, thermal properties, occupancy and outdoor airflow.</p><span className="workflow-meta mono">Conditions · Geometry · Loads</span></li><li><span className="step-number mono">02</span><h3>Follow the heat gains</h3><p>Run the illustrative model. See how the load changes through the day and which components contribute to the peak.</p><span className="workflow-meta mono">Hourly profile · Component breakdown</span></li><li><span className="step-number mono">03</span><h3>Review the reasoning</h3><p>Inspect the formulas and zone contributions. Review assumptions, then export a record of the inputs and results.</p><span className="workflow-meta mono">Calculation audit · Export</span></li></ol></section>
      <section className="landing-start"><div><span className="landing-kicker">Your next step</span><h2>Make the first calculation a clear one.</h2><p>The beginner’s guide explains the inputs, units and results, one step at a time.</p><button className="landing-text-link" onClick={onGuide}>Get to know the workspace <ArrowRight size={16} /></button></div><div className="landing-project-entry"><h3>{project ? 'Your workspace is ready' : 'Start with your building'}</h3><p>{project ? <>Open <strong>{project.name}</strong>, or create a new project with your own spaces.</> : 'Create a project, review the design conditions, and add your first zone.'}</p><Button onClick={onNew} icon={ArrowRight}>Start a new project</Button>{project && <small>Creating a project will ask you to review replacing the current one.</small>}</div></section>
      <aside className="landing-model-note"><span className="model-note-label">About this version</span><p>Mineral currently uses an illustrative steady-state model with demonstration assumptions. It is designed for exploring the workflow; results are not validated for equipment sizing. CLTD/SCL/CLF methods and reference-dataset imports are not yet implemented.</p><button onClick={onGuide}>Understand the model <ArrowUpRight size={15} /></button></aside>
    </main><footer className="landing-footer"><span><Snowflake size={16} />Mineral · Cooling load workspace</span><span className="mono">SI units · Local storage · Illustrative model</span><button onClick={onGuide}>Documentation <ArrowUpRight size={14} /></button></footer></div>
}
